apiVersion: apps/v1
kind: Deployment

metadata:
  name: xpu-pod
  labels:
    app: xpu-pod

spec:
  replicas: 2

  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: xpu-pod

  template: # define the pods specifications
    metadata:
      labels:
        app: xpu-pod
        baidu.com/xpu-count: "1"

    spec:
      containers:
      - name: xpu-pod
        image: ubuntu:20.04
        command:
          - /bin/sleep
          - 10h
        resources:
          limits:
            # MiB
            baidu.com/xpu-mem: 4500

